const tasks = [
  [
    { task: "Sleep", desc: "Wind down and sleep", from: "00:00", to: "06:00" },
    {
      task: "Wake Up",
      desc: "Get out of bed or get dunked on",
      from: "06:00",
      to: "06:10",
    },
    {
      task: "Make Breakfast",
      desc: "Please, anything but junk",
      from: "06:10",
      to: "06:30",
    },
    {
      task: "Eat Breakfast",
      desc: "Eat and watch some news",
      from: "06:30",
      to: "06:40",
    },
    { task: "Exercise", desc: "Morning workout", from: "06:40", to: "07:10" },
    {
      task: "Clean yourself",
      desc: "Get ready for the day",
      from: "07:10",
      to: "07:40",
    },
    {
      task: "Start Homework",
      desc: "Intense homework to wakeup your brain",
      from: "07:40",
      to: "08:10",
    },
    { task: "Relax", desc: "Pause to breathe", from: "08:10", to: "08:25" },
    {
      task: "Journey to School",
      desc: "Enjoy a suave car ride",
      from: "08:25",
      to: "08:45",
    },
    {
      task: "Applied Maths Class",
      desc: "Become a mathematical bureaucrat",
      from: "08:45",
      to: "10:15",
    },
    { task: "Break", desc: "Greet the homies", from: "10:15", to: "10:30" },
    {
      task: "Applied Maths Class",
      desc: "Become a mathematical bureaucrat",
      from: "10:30",
      to: "12:00",
    },
    { task: "Lunch", desc: "Enjoy life", from: "12:00", to: "12:40" },
    {
      task: "Pure Maths Class",
      desc: "Expand your thinking",
      from: "12:40",
      to: "14:10",
    },
    { task: "Break", desc: "Re-greet the homies", from: "14:10", to: "14:20" },
    {
      task: "Pure Maths Class",
      desc: "Expand your thinking",
      from: "14:20",
      to: "15:50",
    },
    {
      task: "Sidequest",
      desc: "Pickup a sidequest",
      from: "15:50",
      to: "16:20",
    },
    {
      task: "Journey Home",
      desc: "Enjoy a turbulent car ride",
      from: "16:20",
      to: "16:40",
    },
    {
      task: "Prepare Dinner",
      desc: "Cook something nice",
      from: "16:40",
      to: "17:10",
    },
    {
      task: "Eat Dinner",
      desc: "Eat and watch some shows",
      from: "17:10",
      to: "17:30",
    },
    {
      task: "Finish homework",
      desc: "Last sprint of the day",
      from: "17:30",
      to: "19:00",
    },
    {
      task: "Play with friends",
      desc: "Its either this or death",
      from: "19:00",
      to: "20:00",
    },
    { task: "Make snack", desc: "Small boost", from: "20:00", to: "20:10" },
    {
      task: "Eat snack",
      desc: "Getting a small boost",
      from: "20:10",
      to: "20:20",
    },
    { task: "Code", desc: "Make something cool", from: "20:20", to: "22:00" },
    { task: "Sleep", desc: "Wind down and sleep", from: "22:00", to: "23:59" },
  ],
  [
    { task: "Sleep", desc: "Wind down and sleep", from: "00:00", to: "06:00" },
    {
      task: "Wake Up",
      desc: "Get out of bed or get dunked on",
      from: "06:00",
      to: "06:10",
    },
    {
      task: "Make Breakfast",
      desc: "Please, anything but junk",
      from: "06:10",
      to: "06:30",
    },
    {
      task: "Eat Breakfast",
      desc: "Eat and watch some news",
      from: "06:30",
      to: "06:40",
    },
    { task: "Exercise", desc: "Morning workout", from: "06:40", to: "07:10" },
    {
      task: "Clean yourself",
      desc: "Get ready for the day",
      from: "07:10",
      to: "07:40",
    },
    {
      task: "Start Homework",
      desc: "Intense homework to wakeup your brain",
      from: "07:40",
      to: "08:10",
    },
    { task: "Relax", desc: "Pause to breathe", from: "08:10", to: "08:25" },
    {
      task: "Journey to School",
      desc: "Enjoy a suave car ride",
      from: "08:25",
      to: "08:45",
    },
    {
      task: "Computer Science Class",
      desc: "Holy abstractions",
      from: "08:45",
      to: "10:15",
    },
    { task: "Break", desc: "Greet the homies", from: "10:15", to: "10:30" },
    {
      task: "Computer Science Class",
      desc: "Become a mathematical bureaucrat",
      from: "10:30",
      to: "12:00",
    },
    { task: "Lunch", desc: "Enjoy life", from: "12:00", to: "12:40" },
    {
      task: "Revise Period",
      desc: "Relearn all you know",
      from: "12:40",
      to: "14:10",
    },
    { task: "Break", desc: "Re-greet the homies", from: "14:10", to: "14:20" },
    {
      task: "Revise Period",
      desc: "Relearn all you know",
      from: "14:20",
      to: "15:50",
    },
    {
      task: "Sidequest",
      desc: "Pickup a sidequest",
      from: "15:50",
      to: "16:20",
    },
    {
      task: "Journey Home",
      desc: "Enjoy a turbulent car ride",
      from: "16:20",
      to: "16:40",
    },
    {
      task: "Prepare Dinner",
      desc: "Cook something nice",
      from: "16:40",
      to: "17:10",
    },
    {
      task: "Eat Dinner",
      desc: "Eat and watch some shows",
      from: "17:10",
      to: "17:30",
    },
    {
      task: "Finish homework",
      desc: "Last sprint of the day",
      from: "17:30",
      to: "19:00",
    },
    {
      task: "Play with friends",
      desc: "Its either this or death",
      from: "19:00",
      to: "20:00",
    },
    { task: "Make snack", desc: "Small boost", from: "20:00", to: "20:10" },
    {
      task: "Eat snack",
      desc: "Getting a small boost",
      from: "20:10",
      to: "20:20",
    },
    { task: "Code", desc: "Make something cool", from: "20:20", to: "22:00" },
    { task: "Sleep", desc: "Wind down and sleep", from: "22:00", to: "23:59" },
  ],
  [
    { task: "Sleep", desc: "Wind down and sleep", from: "00:00", to: "06:00" },
    {
      task: "Wake Up",
      desc: "Get out of bed or get dunked on",
      from: "06:00",
      to: "06:10",
    },
    {
      task: "Make Breakfast",
      desc: "Please, anything but junk",
      from: "06:10",
      to: "06:30",
    },
    {
      task: "Eat Breakfast",
      desc: "Eat and watch some news",
      from: "06:30",
      to: "06:40",
    },
    { task: "Exercise", desc: "Morning workout", from: "06:40", to: "07:10" },
    {
      task: "Clean yourself",
      desc: "Get ready for the day",
      from: "07:10",
      to: "07:40",
    },
    {
      task: "Start Homework",
      desc: "Intense homework to wakeup your brain",
      from: "07:40",
      to: "08:10",
    },
    { task: "Relax", desc: "Pause to breathe", from: "08:10", to: "08:25" },
    {
      task: "Journey to School",
      desc: "Enjoy a suave car ride",
      from: "08:25",
      to: "08:45",
    },
    {
      task: "Pure Maths Class",
      desc: "Expand your thinking",
      from: "08:45",
      to: "10:15",
    },
    { task: "Break", desc: "Greet the homies", from: "10:15", to: "10:30" },
    {
      task: "Computer Science Class",
      desc: "Holy Abstraction",
      from: "10:30",
      to: "12:00",
    },
    { task: "Break", desc: "Re-greet the homies", from: "12:00", to: "12:10" },
    {
      task: "Seminar",
      desc: "Hear but don't listen",
      from: "12:10",
      to: "13:40",
    },
    { task: "Lunch", desc: "Enjoy life", from: "13:40", to: "14:20" },
    {
      task: "Enrichment",
      desc: "Finally, something new",
      from: "14:20",
      to: "15:20",
    },
    {
      task: "Sidequest",
      desc: "Pickup a sidequest",
      from: "15:20",
      to: "15:50",
    },
    {
      task: "Journey Home",
      desc: "Enjoy a turbulent car ride",
      from: "15:50",
      to: "16:10",
    },
    {
      task: "Prepare Dinner",
      desc: "Cook something nice",
      from: "16:10",
      to: "16:40",
    },
    {
      task: "Eat Dinner",
      desc: "Eat and watch some shows",
      from: "16:40",
      to: "17:00",
    },
    {
      task: "Finish homework",
      desc: "Last sprint of the day",
      from: "17:00",
      to: "18:45",
    },
    {
      task: "Play with friends",
      desc: "Its either this or death",
      from: "18:45",
      to: "20:00",
    },
    { task: "Make snack", desc: "Small boost", from: "20:00", to: "20:10" },
    {
      task: "Eat snack",
      desc: "Getting a small boost",
      from: "20:10",
      to: "20:20",
    },
    { task: "Code", desc: "Make something cool", from: "20:20", to: "22:00" },
    { task: "Sleep", desc: "Wind down and sleep", from: "22:00", to: "23:59" },
  ],
  [
    { task: "Sleep", desc: "Wind down and sleep", from: "00:00", to: "06:00" },
    {
      task: "Wake Up",
      desc: "Get out of bed or get dunked on",
      from: "06:00",
      to: "06:10",
    },
    {
      task: "Make Breakfast",
      desc: "Please, anything but junk",
      from: "06:10",
      to: "06:30",
    },
    {
      task: "Eat Breakfast",
      desc: "Eat and watch some news",
      from: "06:30",
      to: "06:40",
    },
    { task: "Exercise", desc: "Morning workout", from: "06:40", to: "07:10" },
    {
      task: "Clean yourself",
      desc: "Get ready for the day",
      from: "07:10",
      to: "07:40",
    },
    {
      task: "Start Homework",
      desc: "Intense homework to wakeup your brain",
      from: "07:40",
      to: "08:10",
    },
    { task: "Relax", desc: "Pause to breathe", from: "08:10", to: "08:25" },
    {
      task: "Journey to School",
      desc: "Enjoy a suave car ride",
      from: "08:25",
      to: "08:45",
    },
    {
      task: "Physics Class",
      desc: "Quirks of the universe",
      from: "08:45",
      to: "10:15",
    },
    { task: "Break", desc: "Greet the homies", from: "10:15", to: "10:30" },
    {
      task: "Physics Class",
      desc: "Quirks of the universe",
      from: "10:30",
      to: "12:00",
    },
    { task: "Lunch", desc: "Enjoy life", from: "12:00", to: "12:40" },
    {
      task: "Revise Period",
      desc: "Relearn all you know",
      from: "12:40",
      to: "14:10",
    },
    { task: "Break", desc: "Re-greet the homies", from: "14:10", to: "14:20" },
    {
      task: "Revise Period",
      desc: "Relearn all you know",
      from: "14:20",
      to: "15:50",
    },
    {
      task: "Sidequest",
      desc: "Pickup a sidequest",
      from: "15:50",
      to: "16:20",
    },
    {
      task: "Journey Home",
      desc: "Enjoy a turbulent car ride",
      from: "16:20",
      to: "16:40",
    },
    {
      task: "Prepare Dinner",
      desc: "Cook something nice",
      from: "16:40",
      to: "17:10",
    },
    {
      task: "Eat Dinner",
      desc: "Eat and watch some shows",
      from: "17:10",
      to: "17:30",
    },
    {
      task: "Finish homework",
      desc: "Last sprint of the day",
      from: "17:30",
      to: "19:00",
    },
    {
      task: "Play with friends",
      desc: "Its either this or death",
      from: "19:00",
      to: "20:00",
    },
    { task: "Make snack", desc: "Small boost", from: "20:00", to: "20:10" },
    {
      task: "Eat snack",
      desc: "Getting a small boost",
      from: "20:10",
      to: "20:20",
    },
    { task: "Code", desc: "Make something cool", from: "20:20", to: "22:00" },
    { task: "Sleep", desc: "Wind down and sleep", from: "22:00", to: "23:59" },
  ],
  [
    { task: "Sleep", desc: "Wind down and sleep", from: "00:00", to: "06:00" },
    {
      task: "Wake Up",
      desc: "Get out of bed or get dunked on",
      from: "06:00",
      to: "06:10",
    },
    {
      task: "Make Breakfast",
      desc: "Please, anything but junk",
      from: "06:10",
      to: "06:30",
    },
    {
      task: "Eat Breakfast",
      desc: "Eat and watch some news",
      from: "06:30",
      to: "06:40",
    },
    { task: "Exercise", desc: "Morning workout", from: "06:40", to: "07:10" },
    {
      task: "Clean yourself",
      desc: "Get ready for the day",
      from: "07:10",
      to: "07:40",
    },
    {
      task: "Start Homework",
      desc: "Intense homework to wakeup your brain",
      from: "07:40",
      to: "08:10",
    },
    { task: "Relax", desc: "Pause to breathe", from: "08:10", to: "08:25" },
    {
      task: "Journey to School",
      desc: "Enjoy a suave car ride",
      from: "08:25",
      to: "08:45",
    },
    {
      task: "The Hub",
      desc: "It's better than what it sounds like",
      from: "08:45",
      to: "10:15",
    },
    { task: "Break", desc: "Greet the homies", from: "10:15", to: "10:30" },
    {
      task: "Revise Period",
      desc: "Become a mathematical bureaucrat",
      from: "10:30",
      to: "12:00",
    },
    { task: "Lunch", desc: "Enjoy life", from: "12:00", to: "12:40" },
    {
      task: "Physics Class",
      desc: "Quirks of the universe",
      from: "12:40",
      to: "14:10",
    },
    { task: "Break", desc: "Re-greet the homies", from: "14:10", to: "14:20" },
    {
      task: "Applied Maths Class",
      desc: "Become a mathematical bureaucrat",
      from: "14:20",
      to: "15:50",
    },
    {
      task: "Sidequest",
      desc: "Pickup a sidequest",
      from: "15:50",
      to: "16:20",
    },
    {
      task: "Journey Home",
      desc: "Enjoy a turbulent car ride",
      from: "16:20",
      to: "16:40",
    },
    {
      task: "Prepare Dinner",
      desc: "Cook something nice",
      from: "16:40",
      to: "17:10",
    },
    {
      task: "Eat Dinner",
      desc: "Eat and watch some shows",
      from: "17:10",
      to: "17:30",
    },
    {
      task: "Finish homework",
      desc: "Last sprint of the day",
      from: "17:30",
      to: "19:00",
    },
    {
      task: "Play with friends",
      desc: "Its either this or death",
      from: "19:00",
      to: "20:00",
    },
    { task: "Make snack", desc: "Small boost", from: "20:00", to: "20:10" },
    {
      task: "Eat snack",
      desc: "Getting a small boost",
      from: "20:10",
      to: "20:20",
    },
    { task: "Code", desc: "Make something cool", from: "20:20", to: "22:00" },
    { task: "Sleep", desc: "Wind down and sleep", from: "22:00", to: "23:59" },
  ],
  [
    { task: "Sleep", desc: "Wind down and sleep", from: "00:00", to: "06:00" },
    {
      task: "Wake Up",
      desc: "Get out of bed or get dunked on",
      from: "06:00",
      to: "06:10",
    },
    {
      task: "Make Breakfast",
      desc: "Please, anything but junk",
      from: "06:10",
      to: "06:30",
    },
    {
      task: "Eat Breakfast",
      desc: "Eat and watch some news",
      from: "06:30",
      to: "06:40",
    },
    { task: "Exercise", desc: "Morning workout", from: "06:40", to: "07:10" },
    {
      task: "Clean yourself",
      desc: "Get ready for the day",
      from: "07:10",
      to: "07:40",
    },
    {
      task: "Start Homework",
      desc: "Intense homework to wakeup your brain",
      from: "07:40",
      to: "08:10",
    },
    { task: "Relax", desc: "Pause to breathe", from: "08:10", to: "08:25" },
    { task: "Coding", desc: "Lock in", from: "08:25", to: "16:40" },
    {
      task: "Prepare Dinner",
      desc: "Cook something nice",
      from: "16:40",
      to: "17:10",
    },
    {
      task: "Eat Dinner",
      desc: "Eat and watch some shows",
      from: "17:10",
      to: "17:30",
    },
    {
      task: "Finish homework",
      desc: "Last sprint of the day",
      from: "17:30",
      to: "19:00",
    },
    {
      task: "Play with friends",
      desc: "Its either this or death",
      from: "19:00",
      to: "20:00",
    },
    { task: "Make snack", desc: "Small boost", from: "20:00", to: "20:10" },
    {
      task: "Eat snack",
      desc: "Getting a small boost",
      from: "20:10",
      to: "20:20",
    },
    { task: "Code", desc: "Make something cool", from: "20:20", to: "22:00" },
    { task: "Sleep", desc: "Wind down and sleep", from: "22:00", to: "23:59" },
  ],
  [
    { task: "Sleep", desc: "Wind down and sleep", from: "00:00", to: "06:00" },
    {
      task: "Wake Up",
      desc: "Get out of bed or get dunked on",
      from: "06:00",
      to: "06:10",
    },
    {
      task: "Make Breakfast",
      desc: "Please, anything but junk",
      from: "06:10",
      to: "06:30",
    },
    {
      task: "Eat Breakfast",
      desc: "Eat and watch some news",
      from: "06:30",
      to: "06:40",
    },
    { task: "Exercise", desc: "Morning workout", from: "06:40", to: "07:10" },
    {
      task: "Clean yourself",
      desc: "Get ready for the day",
      from: "07:10",
      to: "07:40",
    },
    {
      task: "Start Homework",
      desc: "Intense homework to wakeup your brain",
      from: "07:40",
      to: "08:10",
    },
    { task: "Relax", desc: "Pause to breathe", from: "08:10", to: "08:25" },
    { task: "Coding", desc: "Lock in", from: "08:25", to: "16:00" },
    {
      task: "Prepare Dinner",
      desc: "Cook something nice",
      from: "16:00",
      to: "16:30",
    },
    {
      task: "Eat Dinner",
      desc: "Eat and watch some shows",
      from: "16:30",
      to: "16:50",
    },
    {
      task: "Finish homework",
      desc: "Last sprint of the day",
      from: "16:50",
      to: "18:20",
    },
    {
      task: "Play with friends",
      desc: "Its either this or death",
      from: "18:20",
      to: "20:00",
    },
    { task: "Make snack", desc: "Small boost", from: "20:00", to: "20:10" },
    {
      task: "Eat snack",
      desc: "Getting a small boost",
      from: "20:10",
      to: "20:20",
    },
    { task: "Code", desc: "Make something cool", from: "20:20", to: "22:00" },
    { task: "Sleep", desc: "Wind down and sleep", from: "22:00", to: "23:59" },
  ],
];
